module.exports = [
  {value: '1101', label: 'Australia'},
  {value: '1601', label: 'Adelie Land (France)'},
  {value: '7201', label: 'Afghanistan'},
  {value: '2708', label: 'Aland Islands'},
  {value: '3201', label: 'Albania'},
  {value: '4101', label: 'Algeria'},
  {value: '3101', label: 'Andorra'},
  {value: '9201', label: 'Angola'},
  {value: '8401', label: 'Anguilla'},
  {value: '8402', label: 'Antigua and Barbuda'},
  {value: '8201', label: 'Argentina'},
  {value: '1602', label: 'Argentinian Antarctic Territory'},
  {value: '7202', label: 'Armenia'},
  {value: '8403', label: 'Aruba'},
  {value: '1603', label: 'Australian Antarctic Territory'},
  {value: '1199', label: 'Australian External Territories, nec'},
  {value: '2301', label: 'Austria'},
  {value: '7203', label: 'Azerbaijan'},
  {value: '8404', label: 'Bahamas'},
  {value: '4201', label: 'Bahrain'},
  {value: '7101', label: 'Bangladesh'},
  {value: '8405', label: 'Barbados'},
  {value: '3301', label: 'Belarus'},
  {value: '2302', label: 'Belgium'},
  {value: '8301', label: 'Belize'},
  {value: '9101', label: 'Benin'},
  {value: '8101', label: 'Bermuda'},
  {value: '7102', label: 'Bhutan'},
  {value: '8202', label: 'Bolivia, Plurinational State of'},
  {value: '8433', label: 'Bonaire, Sint Eustatius and Saba'},
  {value: '3202', label: 'Bosnia and Herzegovina'},
  {value: '9202', label: 'Botswana'},
  {value: '8203', label: 'Brazil'},
  {value: '1604', label: 'British Antarctic Territory'},
  {value: '5201', label: 'Brunei Darussalam'},
  {value: '3203', label: 'Bulgaria'},
  {value: '9102', label: 'Burkina Faso'},
  {value: '9203', label: 'Burundi'},
  {value: '9104', label: 'Cabo Verde'},
  {value: '5102', label: 'Cambodia'},
  {value: '9103', label: 'Cameroon'},
  {value: '8102', label: 'Canada'},
  {value: '8406', label: 'Cayman Islands'},
  {value: '9105', label: 'Central African Republic'},
  {value: '9106', label: 'Chad'},
  {value: '8204', label: 'Chile'},
  {value: '1605', label: 'Chilean Antarctic Territory'},
  {value: '6101', label: 'China (excludes SARs and Taiwan)'},
  {value: '8205', label: 'Colombia'},
  {value: '9204', label: 'Comoros'},
  {value: '9108', label: 'Congo, Democratic Republic of'},
  {value: '9107', label: 'Congo, Republic of'},
  {value: '1501', label: 'Cook Islands'},
  {value: '8302', label: 'Costa Rica'},
  {value: '9111', label: "Cote d'Ivoire"},
  {value: '3204', label: 'Croatia'},
  {value: '8407', label: 'Cuba'},
  {value: '8434', label: 'Curacao'},
  {value: '3205', label: 'Cyprus'},
  {value: '3302', label: 'Czech Republic'},
  {value: '2401', label: 'Denmark'},
  {value: '9205', label: 'Djibouti'},
  {value: '8408', label: 'Dominica'},
  {value: '8411', label: 'Dominican Republic'},
  {value: '8206', label: 'Ecuador'},
  {value: '4102', label: 'Egypt'},
  {value: '8303', label: 'El Salvador'},
  {value: '2102', label: 'England'},
  {value: '9112', label: 'Equatorial Guinea'},
  {value: '9206', label: 'Eritrea'},
  {value: '3303', label: 'Estonia'},
  {value: '9207', label: 'Ethiopia'},
  {value: '8207', label: 'Falkland Islands'},
  {value: '2402', label: 'Faroe Islands'},
  {value: '1502', label: 'Fiji'},
  {value: '2403', label: 'Finland'},
  {value: '3206', label: 'Former Yugoslav Republic of Macedonia (FYROM)'},
  {value: '2303', label: 'France'},
  {value: '8208', label: 'French Guiana'},
  {value: '1503', label: 'French Polynesia'},
  {value: '9113', label: 'Gabon'},
  {value: '9114', label: 'Gambia'},
  {value: '4202', label: 'Gaza Strip and West Bank'},
  {value: '7204', label: 'Georgia'},
  {value: '2304', label: 'Germany'},
  {value: '9115', label: 'Ghana'},
  {value: '3102', label: 'Gibraltar'},
  {value: '3207', label: 'Greece'},
  {value: '2404', label: 'Greenland'},
  {value: '8412', label: 'Grenada'},
  {value: '8413', label: 'Guadeloupe'},
  {value: '1401', label: 'Guam'},
  {value: '8304', label: 'Guatemala'},
  {value: '2107', label: 'Guernsey'},
  {value: '9116', label: 'Guinea'},
  {value: '9117', label: 'Guinea-Bissau'},
  {value: '8211', label: 'Guyana'},
  {value: '8414', label: 'Haiti'},
  {value: '3103', label: 'Holy See'},
  {value: '8305', label: 'Honduras'},
  {value: '6102', label: 'Hong Kong (SAR of China)'},
  {value: '3304', label: 'Hungary'},
  {value: '2405', label: 'Iceland'},
  {value: '7103', label: 'India'},
  {value: '5202', label: 'Indonesia'},
  {value: '4203', label: 'Iran'},
  {value: '4204', label: 'Iraq'},
  {value: '2201', label: 'Ireland'},
  {value: '2103', label: 'Isle of Man'},
  {value: '4205', label: 'Israel'},
  {value: '3104', label: 'Italy'},
  {value: '8415', label: 'Jamaica'},
  {value: '6201', label: 'Japan'},
  {value: '2108', label: 'Jersey'},
  {value: '4206', label: 'Jordan'},
  {value: '7205', label: 'Kazakhstan'},
  {value: '9208', label: 'Kenya'},
  {value: '1402', label: 'Kiribati'},
  {value: '6202', label: "Korea, Democratic People's Republic of (North)"},
  {value: '6203', label: 'Korea, Republic of (South)'},
  {value: '3216', label: 'Kosovo'},
  {value: '4207', label: 'Kuwait'},
  {value: '7206', label: 'Kyrgyzstan'},
  {value: '5103', label: 'Laos'},
  {value: '3305', label: 'Latvia'},
  {value: '4208', label: 'Lebanon'},
  {value: '9211', label: 'Lesotho'},
  {value: '9118', label: 'Liberia'},
  {value: '4103', label: 'Libya'},
  {value: '2305', label: 'Liechtenstein'},
  {value: '3306', label: 'Lithuania'},
  {value: '2306', label: 'Luxembourg'},
  {value: '6103', label: 'Macau (SAR of China)'},
  {value: '9212', label: 'Madagascar'},
  {value: '9213', label: 'Malawi'},
  {value: '5203', label: 'Malaysia'},
  {value: '7104', label: 'Maldives'},
  {value: '9121', label: 'Mali'},
  {value: '3105', label: 'Malta'},
  {value: '1403', label: 'Marshall Islands'},
  {value: '8416', label: 'Martinique'},
  {value: '9122', label: 'Mauritania'},
  {value: '9214', label: 'Mauritius'},
  {value: '9215', label: 'Mayotte'},
  {value: '8306', label: 'Mexico'},
  {value: '1404', label: 'Micronesia, Federated States of'},
  {value: '3208', label: 'Moldova'},
  {value: '2307', label: 'Monaco'},
  {value: '6104', label: 'Mongolia'},
  {value: '3214', label: 'Montenegro'},
  {value: '8417', label: 'Montserrat'},
  {value: '4104', label: 'Morocco'},
  {value: '9216', label: 'Mozambique'},
  {value: '5101', label: 'Myanmar, The Republic of the Union of '},
  {value: '9217', label: 'Namibia'},
  {value: '1405', label: 'Nauru'},
  {value: '7105', label: 'Nepal'},
  {value: '2308', label: 'Netherlands'},
  {value: '1301', label: 'New Caledonia'},
  {value: '1201', label: 'New Zealand'},
  {value: '8307', label: 'Nicaragua'},
  {value: '9123', label: 'Niger'},
  {value: '9124', label: 'Nigeria'},
  {value: '1504', label: 'Niue'},
  {value: '1102', label: 'Norfolk Island'},
  {value: '2104', label: 'Northern Ireland'},
  {value: '1406', label: 'Northern Mariana Islands'},
  {value: '2406', label: 'Norway'},
  {value: '4211', label: 'Oman'},
  {value: '7106', label: 'Pakistan'},
  {value: '1407', label: 'Palau'},
  {value: '8308', label: 'Panama'},
  {value: '1302', label: 'Papua New Guinea'},
  {value: '8212', label: 'Paraguay'},
  {value: '8213', label: 'Peru'},
  {value: '5204', label: 'Philippines'},
  {value: '1513', label: 'Pitcairn Islands'},
  {value: '3307', label: 'Poland'},
  {value: '1599', label: 'Polynesia (excludes Hawaii), nec'},
  {value: '3106', label: 'Portugal'},
  {value: '8421', label: 'Puerto Rico'},
  {value: '4212', label: 'Qatar'},
  {value: '1606', label: 'Queen Maud Land (Norway)'},
  {value: '9218', label: 'Reunion'},
  {value: '3211', label: 'Romania'},
  {value: '1607', label: 'Ross Dependency (New Zealand)'},
  {value: '3308', label: 'Russian Federation'},
  {value: '9221', label: 'Rwanda'},
  {value: '1505', label: 'Samoa'},
  {value: '1506', label: 'Samoa, American'},
  {value: '3107', label: 'San Marino'},
  {value: '9125', label: 'Sao Tome and Principe'},
  {value: '4213', label: 'Saudi Arabia'},
  {value: '2105', label: 'Scotland'},
  {value: '9126', label: 'Senegal'},
  {value: '3215', label: 'Serbia'},
  {value: '9223', label: 'Seychelles'},
  {value: '9127', label: 'Sierra Leone'},
  {value: '5205', label: 'Singapore'},
  {value: '8435', label: 'Sint Maarten (Dutch part)'},
  {value: '3311', label: 'Slovakia'},
  {value: '3212', label: 'Slovenia'},
  {value: '1303', label: 'Solomon Islands'},
  {value: '9224', label: 'Somalia'},
  {value: '9225', label: 'South Africa'},
  {value: '8299', label: 'South America, nec'},
  {value: '4111', label: 'South Sudan'},
  {value: '9299', label: 'Southern and East Africa, nec'},
  {value: '3108', label: 'Spain'},
  {value: '4108', label: 'Spanish North Africa'},
  {value: '7107', label: 'Sri Lanka'},
  {value: '8431', label: 'St Barthelemy'},
  {value: '9222', label: 'St Helena'},
  {value: '8422', label: 'St Kitts and Nevis'},
  {value: '8423', label: 'St Lucia'},
  {value: '8432', label: 'St Martin (French part)'},
  {value: '8103', label: 'St Pierre and Miquelon'},
  {value: '8424', label: 'St Vincent and the Grenadines'},
  {value: '4105', label: 'Sudan'},
  {value: '8214', label: 'Suriname'},
  {value: '9226', label: 'Swaziland'},
  {value: '2707', label: 'Sweden'},
  {value: '2311', label: 'Switzerland'},
  {value: '4214', label: 'Syria'},
  {value: '6105', label: 'Taiwan'},
  {value: '7207', label: 'Tajikistan'},
  {value: '9227', label: 'Tanzania'},
  {value: '5104', label: 'Thailand'},
  {value: '5206', label: 'Timor-Leste'},
  {value: '9128', label: 'Togo'},
  {value: '1507', label: 'Tokelau'},
  {value: '1508', label: 'Tonga'},
  {value: '8425', label: 'Trinidad and Tobago'},
  {value: '4106', label: 'Tunisia'},
  {value: '4215', label: 'Turkey'},
  {value: '7208', label: 'Turkmenistan'},
  {value: '8426', label: 'Turks and Caicos Islands'},
  {value: '1511', label: 'Tuvalu'},
  {value: '9228', label: 'Uganda'},
  {value: '3312', label: 'Ukraine'},
  {value: '4216', label: 'United Arab Emirates'},
  {value: '8104', label: 'United States of America'},
  {value: '8215', label: 'Uruguay'},
  {value: '7211', label: 'Uzbekistan'},
  {value: '1304', label: 'Vanuatu'},
  {value: '8216', label: 'Venezuela, Bolivarian Republic of'},
  {value: '5105', label: 'Vietnam'},
  {value: '8427', label: 'Virgin Islands, British '},
  {value: '8428', label: 'Virgin Islands, United States'},
  {value: '2106', label: 'Wales'},
  {value: '1512', label: 'Wallis and Futuna'},
  {value: '4107', label: 'Western Sahara'},
  {value: '4217', label: 'Yemen'},
  {value: '9231', label: 'Zambia'},
  {value: '9232', label: 'Zimbabwe'}
]
